### ISSUE TITLE
Do Not Open This ... VIRUS/HACK warning! 

### ISSUE THREAD

**Issue by thezetas** [m3g4nz/meganz#4]
Do Not Open This ... VIRUS/HACK warning!

**Comment by rusdino** [comment]
do you also come here by discord?

**Comment by NekoCyan** [comment]
For sure.

**Comment by TheEnigmaBlade** [comment]
Github is being slow today. I reported this account two hours ago.

**Comment by DeathHound6** [comment]
I'm here from Discord too. Github should hopefully ban the account/delete the repo within a few hours

**Comment by rusdino** [comment]
wow, what a coincidence, well it is pretty widespread now, gonna be pretty hard to track the first cause, how bout location? are you guys also from Asia or Southeast Asia? it doesn't give an idea about the creator, but we should know the target by it

**Comment by DeathHound6** [comment]
https://www.virustotal.com/gui/file/a1167c6d778ee725e57b19e99465abeeb8bcfb5e5888c4b2c16e70c23bedffbe/detection

**Comment by DeathHound6** [comment]
> wow, what a coincidence, well it is pretty widespread now, gonna be pretty hard to track the first cause, how bout location? are you guys also from Asia or Southeast Asia? it doesn't give an idea about the creator, but we should know the target by it

I'm from the UK (Europe) and the person who was posting this that I saw was in a 12.5k member server. I banned them for it obvs

**Comment by BitBl4st321** [comment]
Its a RAT, calls back to Russia. 
https://any.run/report/a1167c6d778ee725e57b19e99465abeeb8bcfb5e5888c4b2c16e70c23bedffbe/0bd64b03-0f5e-4203-9235-aaee3c0b1ba6

4056 | AppLaunch.exe | 193.106.191.253:34189 | LLC Kras-Host | RU
-- | -- | -- | -- | --

**Comment by TheHandsomeYoni** [comment]
Be careful you all
https://www.virustotal.com/gui/file/873de83e45b45a9fc93f387e1243ba71e213b5cd8398267bdf0f4cae20d8be69
